name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@DeltaKroneckerGithub"
    type: ss
    server: "57.128.191.90"
    port: 8388
    cipher: "2022-blake3-aes-256-gcm"
    password: "R532mRBv3acPAGakeITDQWJRxyym0pxqvzJPmWCFwHU="
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "188.132.183.233"
    port: 8081
    uuid: "f1449968-0329-468b-b56b-1c573ac2a767"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "EJKcPSl0dv7mtU26gg6tUmKPw_aDvO2AHraRgNn6B14"
      short-id: "425ba80cd1a821a8"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "poe.com"
    port: 443
    uuid: "5f1fc730-c184-415c-932b-37c8812c8736"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yor.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "yor.pages.dev"
  - name: "@DeltaKroneckerGithub"
    type: ss
    server: "103.186.155.130"
    port: 38388
    cipher: "aes-256-cfb"
    password: "Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV"
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "yesok42v1.ip4exordir.shop"
    port: 8880
    uuid: "8dc7722c-2767-4eea-a28b-2f8daacc07e3"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "223.16.138.113"
    port: 10002
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.jpmj.dev"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³ @WangCai2"
      headers:
        Host: "sni.jpmj.dev"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "51.89.165.128"
    port: 2096
    uuid: "d5f2b8ad-5ee4-41fe-95e9-7adc1acb0549"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "play.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "K0iITauuYEqIayR3IB5Ny8MVKyORDJ65rUSHc3tLe1E"
      short-id: "42c0b628ba6a42a9"
  - name: "@DeltaKroneckerGithub"
    type: vmess
    server: "104.21.46.157"
    port: 443
    uuid: "4115f84d-3b03-4b03-babf-21b36b2f9c03"
    alterId: 0
    cipher: "auto"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "BBGTr.7777198.Xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/GgigazFGDLgFWDItkD5XgXAL"
      headers:
        Host: "BBGtR.7777198.XyZ"
  - name: "@DeltaKroneckerGithub"
    type: ss
    server: "103.186.154.65"
    port: 38388
    cipher: "aes-256-cfb"
    password: "Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV"
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: ss
    server: "103.186.155.103"
    port: 38388
    cipher: "aes-256-cfb"
    password: "Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV"
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "vvbggs.988988.shop"
    port: 443
    uuid: "9e308743-bc58-4109-b8a8-c2c686959c65"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vvbggs.988988.shop"
    network: ws
    ws-opts:
      path: "/I4W63AAjPkpe1D3pAvPtZpEoeO"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "77.110.120.225"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.dynv6.net"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³@WangCai2"
      headers:
        Host: "sni.111000.dynv6.net"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "195.200.16.70"
    port: 2053
    uuid: "Telegram"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tn1rr.qzz.io"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/sg-lnd"
      headers:
        Host: "tn1rr.qzz.io"
  - name: "@DeltaKroneckerGithub"
    type: ss
    server: "103.97.203.227"
    port: 990
    cipher: "chacha20-ietf-poly1305"
    password: "ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44="
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "159.203.144.233"
    port: 8443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³@WangCai2"
      headers:
        Host: "sni.111000.indevs.in"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "v2.dabache.top"
    port: 2053
    uuid: "e5f8a9f6-f164-479b-b3b5-b90f213c7145"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ir1.airpanel.top"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "ir1.airpanel.top"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "57.128.179.254"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³ @WangCai2"
      headers:
        Host: "sni.111000.indevs.in"
  - name: "@DeltaKroneckerGithub"
    type: trojan
    server: "nhj.1jj.ccwu.cc"
    port: 443
    password: "4e45c1b4-9107-45dd-9995-cdf7cbb44d9d"
    sni: "nhj.1jj.ccwu.cc"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/y1moM5CyNvYMZlzsYHmsMrnO"
      headers:
        Host: "nhj.1jj.ccwu.cc"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "77.73.68.252"
    port: 23335
    uuid: "e384913f-8863-47b4-8858-a84b68abb4a6"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "icloud.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "7Gi8eiUU9TIVbGuvSU16gl5-Aqt7tcCSB9x6CSxyvik"
      short-id: "67b1e94e4dd1ef90"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"

rules:
  - MATCH,PROXY
