name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "afrcloud22.mmv.kr"
    port: 443
    uuid: "5c46707f-c348-4b10-b36d-74c5e3f9485c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "afrcloud22.mmv.kr"
    network: ws
    ws-opts:
      path: "/143.244.190.195=443"
      headers:
        Host: "afrcloud22.mmv.kr"
  - name: "@DeltaKroneckerGithub"
    type: ss
    server: "217.30.10.70"
    port: 9020
    cipher: "aes-256-cfb"
    password: "BNmAXXxAHYpTRdzu"
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "afrcloud22.mmv.kr"
    port: 443
    uuid: "ad9184a3-1d85-4493-9bf9-55b4cdef9d9a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "afrcloud22.mmv.kr"
    network: ws
    ws-opts:
      path: "/143.198.31.221=443"
      headers:
        Host: "afrcloud22.mmv.kr"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "57.129.137.58"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    network: ws
    ws-opts:
      path: "/?ed=2560&telegramðŸ‡¨ðŸ‡³+@V2rayBaaz"
      headers:
        Host: "sni.111000.indevs.in"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "nodejs.org"
    port: 443
    uuid: "a6430e91-38ad-4254-b7db-d1fba6efd9e3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "afrcloud22.mmv.kr"
    network: ws
    ws-opts:
      path: "/129.146.254.25:443"
      headers:
        Host: "afrcloud22.mmv.kr"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "92.118.10.56"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.v6.navy"
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "sni.111000.v6.navy"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "107.189.17.120"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?Telegram%F0%9F%87%A8%F0%9F%87%B3%40WangCai2="
      headers:
        Host: "sni.111000.indevs.in"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "45.15.127.107"
    port: 443
    uuid: "8df8d701-38b4-5175-89ef-7447a1250e67"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "eh.vk.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "3Q2wyMPpUbyfw7rmNxL25nnsNDmK9mHqcumAxYIGKVk"
      short-id: "e3"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "5.10.247.138"
    port: 2096
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "sni.111000.indevs.in"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "93.152.207.11"
    port: 443
    uuid: "TelegramðŸ‡¨ðŸ‡³@WangCai2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tn1rr.qzz.io"
    network: ws
    ws-opts:
      path: "/sg-lnd"
      headers:
        Host: "tn1rr.qzz.io"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "135.84.73.160"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.dynv6.net"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³@WangCai2"
      headers:
        Host: "sni.111000.dynv6.net"
  - name: "@DeltaKroneckerGithub"
    type: ss
    server: "imap.roomyinmita.name"
    port: 40565
    cipher: "chacha20-ietf-poly1305"
    password: "zPbZwy4CsNmSmhGYjoUW47iRgnK7US3cZ9g7o5YefnnTAMzk74upYV8k29XdQaefPwGM7HAmhvqLXSovVA1HH8L8podSAZ3X"
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: vmess
    server: "jmkl.6hh.ccwu.cc"
    port: 80
    uuid: "5f6c3f92-7220-4275-b34d-57c04db3f967"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/KnuT4XBUucXkOSONBms"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "45.131.211.28"
    port: 2096
    uuid: "Telegram%F0%9F%87%A8%F0%9F%87%B3%20%40WangCai2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tn1rr.qzz.io"
    network: ws
    ws-opts:
      path: "/sg-lnd"
      headers:
        Host: "tn1rr.qzz.io"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "afrcloud22.mmv.kr"
    port: 443
    uuid: "3b0d71f7-6202-4526-b2de-8eee4bbebcac"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "afrcloud22.mmv.kr"
    network: ws
    ws-opts:
      path: "/146.235.199.164=443"
      headers:
        Host: "afrcloud22.mmv.kr"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "192.145.29.34"
    port: 443
    uuid: "Telegram%F0%9F%87%A8%F0%9F%87%B3%20%40WangCai2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tn1rr.qzz.io"
    network: ws
    ws-opts:
      path: "/sg-lnd"
      headers:
        Host: "tn1rr.qzz.io"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "151.115.96.243"
    port: 7242
    uuid: "859b7d71-a9fc-4234-8e03-42eb876a170a"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "modily.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jGmjU0vrRXCnIwn0rVatYKf5ihWZhMvqidp2ceY1QAM"
      short-id: "8c01e365"
  - name: "@DeltaKroneckerGithub"
    type: ss
    server: "103.186.155.119"
    port: 38388
    cipher: "aes-256-cfb"
    password: "Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV"
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: vmess
    server: "104.21.58.101"
    port: 80
    uuid: "4115f84d-3b03-4b03-babf-21b36b2f9c03"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/GgigazFGDLgFWDItkD5XgXAL"
      headers:
        Host: "X3e.O09.inDEVS.In"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "57.128.177.185"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³ @WangCai2"
      headers:
        Host: "sni.111000.indevs.in"
  - name: "@DeltaKroneckerGithub"
    type: vless
    server: "103.219.194.43"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³+@WangCai2"
      headers:
        Host: "sni.111000.indevs.in"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"

rules:
  - MATCH,PROXY
