mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 178.22.122.100
    - 185.51.200.2
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.google/dns-query
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - https://cloudflare-dns.com/dns-query
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - https://dns.quad9.net/dns-query
    - tls://9.9.9.9:853
    - https://doh.opendns.com/dns-query
    - tls://208.67.222.222:853
    - https://dns.adguard.com/dns-query
    - tls://94.140.14.14:853

proxies:
  - name: "Delta-Kronecker-ss-1073"
    type: ss
    server: "switcher-nick-croquet.freesocks.work"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "RFK38Cg7APneSB5cWDcpbm"
    udp: true
  - name: "Delta-Kronecker-vless-754"
    type: vless
    server: "144.31.128.67"
    port: 443
    uuid: "8664a37d-40c9-47f0-8619-d9199651be2c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nlcdn12.suio.me"
  - name: "Delta-Kronecker-vless-674"
    type: vless
    server: "172.64.155.209"
    port: 2096
    uuid: "3f0f36f5-f091-45c5-88c9-4bcc545b922c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "hetz.x-smm.com"
    network: ws
    ws-opts:
      path: "/45.76.183.217=49292"
      headers:
        Host: "hetz.x-smm.com"
  - name: "Delta-Kronecker-vless-594"
    type: vless
    server: "159.69.162.184"
    port: 42122
    uuid: "00000000-0000-4000-8000-000000000000"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sub.mot.ip-ddns.com"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "sub.mot.ip-ddns.com"
  - name: "Delta-Kronecker-vless-024"
    type: vless
    server: "94.130.132.223"
    port: 443
    uuid: "0ecc93f5-f30d-47a2-a763-3efeb2a00cc8"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "rapidpars.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "XwmblvweauAJK87G-he0C5OQ-S4Czs1X5BXnbJ7UkiU"
      short-id: "661ee8b0696b45"
  - name: "Delta-Kronecker-ss-490"
    type: ss
    server: "103.186.154.156"
    port: 38388
    cipher: "aes-256-cfb"
    password: "Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV"
    udp: true
  - name: "Delta-Kronecker-vmess-009"
    type: vmess
    server: "47.243.135.74"
    port: 55185
    uuid: "1375985e-334a-4c25-8f64-52a182bc8037"
    alterId: 0
    cipher: "auto"
    udp: true
    network: ws
    ws-opts:
      path: "/Notif_Chat"
  - name: "Delta-Kronecker-ss-570"
    type: ss
    server: "103.186.154.244"
    port: 38388
    cipher: "aes-256-cfb"
    password: "Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV"
    udp: true
  - name: "Delta-Kronecker-vless-2161"
    type: vless
    server: "89.19.44.239"
    port: 2053
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³@WangCai2"
      headers:
        Host: "sni.111000.indevs.in"
  - name: "Delta-Kronecker-vless-1489"
    type: vless
    server: "141.94.221.119"
    port: 8443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.v6.navy"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³ @WangCai2"
      headers:
        Host: "sni.111000.v6.navy"
  - name: "Delta-Kronecker-trojan-663"
    type: trojan
    server: "37.235.49.209"
    port: 28099
    password: "qmBSKnAl6LYi9%3Dz23Rs.Z"
    sni: "celestialcorset.crystalhamster.click"
    skip-cert-verify: true
    udp: true
  - name: "Delta-Kronecker-ss-1170"
    type: ss
    server: "57.129.140.88"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "k1v5g9FefdoO"
    udp: true

proxy-groups:
  # Top-level selector â€” only logical groups shown here
  - name: "PROXY"
    type: select
    proxies:
      - "Load Balance"
      - "Auto"
      - "Fallback"
      - DIRECT

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    proxies:
      - "Delta-Kronecker-ss-1073"
      - "Delta-Kronecker-vless-754"
      - "Delta-Kronecker-vless-674"
      - "Delta-Kronecker-vless-594"
      - "Delta-Kronecker-vless-024"
      - "Delta-Kronecker-ss-490"
      - "Delta-Kronecker-vmess-009"
      - "Delta-Kronecker-ss-570"
      - "Delta-Kronecker-vless-2161"
      - "Delta-Kronecker-vless-1489"
      - "Delta-Kronecker-trojan-663"
      - "Delta-Kronecker-ss-1170"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    lazy: true
    proxies:
      - "Delta-Kronecker-ss-1073"
      - "Delta-Kronecker-vless-754"
      - "Delta-Kronecker-vless-674"
      - "Delta-Kronecker-vless-594"
      - "Delta-Kronecker-vless-024"
      - "Delta-Kronecker-ss-490"
      - "Delta-Kronecker-vmess-009"
      - "Delta-Kronecker-ss-570"
      - "Delta-Kronecker-vless-2161"
      - "Delta-Kronecker-vless-1489"
      - "Delta-Kronecker-trojan-663"
      - "Delta-Kronecker-ss-1170"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    lazy: true
    proxies:
      - "Delta-Kronecker-ss-1073"
      - "Delta-Kronecker-vless-754"
      - "Delta-Kronecker-vless-674"
      - "Delta-Kronecker-vless-594"
      - "Delta-Kronecker-vless-024"
      - "Delta-Kronecker-ss-490"
      - "Delta-Kronecker-vmess-009"
      - "Delta-Kronecker-ss-570"
      - "Delta-Kronecker-vless-2161"
      - "Delta-Kronecker-vless-1489"
      - "Delta-Kronecker-trojan-663"
      - "Delta-Kronecker-ss-1170"

rules:
  - MATCH,PROXY
