name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "Delta-Kronecker-trojan-1159"
    type: trojan
    server: "80.93.202.178"
    port: 2096
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "Delta-Kronecker-trojan-469"
    type: trojan
    server: "172.64.35.159"
    port: 443
    password: "auto"
    sni: "trojanmz.pages.dev"
    skip-cert-verify: true
    udp: true
  - name: "Delta-Kronecker-vless-3042"
    type: vless
    server: "185.241.195.29"
    port: 5443
    uuid: "f8692a50-9593-482f-9d33-4927df87f978"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "yandex.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "GhzR6-mSTnA4t-2flSoiI8sC4jdAFqcAXCompYn71w0"
      short-id: "598706ee32cea0ea"
  - name: "Delta-Kronecker-vless-3962"
    type: vless
    server: "osn.takovpn.ru"
    port: 443
    uuid: "32939076-7490-4484-a2db-d91de1899416"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "www.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ihtXyG0UidSbXjvCJXUhABwZGCCB62DUsVBFn_qVd3g"
      short-id: "97"
  - name: "Delta-Kronecker-vless-1248"
    type: vless
    server: "185.7.240.238"
    port: 2096
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.jpmj.dev"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³@WangCai2"
      headers:
        Host: "sni.jpmj.dev"
  - name: "Delta-Kronecker-trojan-1008"
    type: trojan
    server: "159.242.242.178"
    port: 2096
    password: "d6b8011a-c725-435a-9fec-bf6d3530392c"
    sni: "vle.amclubdns.dpdns.org"
    skip-cert-verify: true
    udp: true
  - name: "Delta-Kronecker-vless-4325"
    type: vless
    server: "afrcloud22.mmv.kr"
    port: 443
    uuid: "b0914021-27a9-432f-86b4-d4a4c4e8d203"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "afrcloud22.mmv.kr"
    network: ws
    ws-opts:
      path: "/121.165.101.69=19413"
      headers:
        Host: "afrcloud22.mmv.kr"
  - name: "Delta-Kronecker-vless-2243"
    type: vless
    server: "5.34.179.145"
    port: 3443
    uuid: "92c2d474-5076-4bb5-adef-04ee0f94094d"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "CsUm6jBZvd5KzFN8Klm9KYF5kiUmztspcA9InbcnwXM"
      short-id: "e49b4e3d5f46d5c2"
  - name: "Delta-Kronecker-vless-324"
    type: vless
    server: "104.16.250.22"
    port: 2053
    uuid: "e5f8a9f6-f164-479b-b3b5-b90f213c7145"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ir1.airpanel.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "ir1.airpanel.top"
  - name: "Delta-Kronecker-vless-3677"
    type: vless
    server: "84.201.184.6"
    port: 443
    uuid: "f999c0f3-2efc-4ff4-8262-bc4554a19d1a"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "api-maps.yandex.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "dTsRKJN6v03ir1RDMk-DglS9TKiGXRPh1HYbbZXZuUQ"
      short-id: "46761921684ac921"
  - name: "Delta-Kronecker-vless-3777"
    type: vless
    server: "129.154.223.89"
    port: 15800
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³ @WangCai2"
      headers:
        Host: "sni.111000.indevs.in"
  - name: "Delta-Kronecker-vless-217"
    type: vless
    server: "dd.openaccessnode.com"
    port: 5228
    uuid: "75193bef-8d8f-e823-41e0-2dd083dc1399"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "mtalk.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ECxm-BdHYhxYK9MtN33NkkrFSdFZXp-OB-yhN8AleRY"
      short-id: "a62d513cd709744a"
  - name: "Delta-Kronecker-ss-2373"
    type: ss
    server: "154.205.159.100"
    port: 990
    cipher: "chacha20-ietf-poly1305"
    password: "ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44="
    udp: true
  - name: "Delta-Kronecker-vless-3895"
    type: vless
    server: "144.31.100.120"
    port: 443
    uuid: "01e92d42-9bbd-4e77-82a5-f64402c2e161"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "www.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ihtXyG0UidSbXjvCJXUhABwZGCCB62DUsVBFn_qVd3g"
      short-id: "352e3a94"
  - name: "Delta-Kronecker-vless-3811"
    type: vless
    server: "osn.takovpn.ru"
    port: 443
    uuid: "62cc6c7f-c060-4275-a1a0-7c823d27797d"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "www.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ihtXyG0UidSbXjvCJXUhABwZGCCB62DUsVBFn_qVd3g"
      short-id: "54c71eb172a3"
  - name: "Delta-Kronecker-vless-3008"
    type: vless
    server: "130.193.59.133"
    port: 443
    uuid: "6e67163a-95e2-422b-b966-774920649662"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "yandex.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "_CjW0Khlrr5z5oc9Oy6-w2ZEanz-zMBktVn5EOX9oTM"
      short-id: "6419bed7fd0a2cff"
  - name: "Delta-Kronecker-vless-1476"
    type: vless
    server: "208.103.161.6"
    port: 2096
    uuid: "26524cce-d514-4014-a426-365fb266a14d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "WangCai.443888.xyz"
    network: ws
    ws-opts:
      path: "/danfeng?ed=2560&TelegramðŸ‡¨ðŸ‡³@WangCai2"
      headers:
        Host: "WangCai.443888.xyz"
  - name: "Delta-Kronecker-vless-2037"
    type: vless
    server: "hu.jojack.ru"
    port: 443
    uuid: "eb071647-72a6-46be-8e89-ff3d228d52f6"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "hu.jojack.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "FkmYFobwxLMLEktYXywmjthuEYCZggITsxwPNasTKUg"
      short-id: "3f200574d011010f"
  - name: "Delta-Kronecker-trojan-002"
    type: trojan
    server: "188.116.22.217"
    port: 2083
    password: "0zmdDXd0Qt5ff_7Qg67R-Rtq4Tmt4c"
    sni: "xo.e0f.cx"
    skip-cert-verify: true
    udp: true
  - name: "Delta-Kronecker-vless-1896"
    type: vless
    server: "62.84.96.201"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³ @WangCai2"
      headers:
        Host: "sni.111000.indevs.in"
  - name: "Delta-Kronecker-trojan-1180"
    type: trojan
    server: "160.16.124.55"
    port: 5553
    password: "2274c52572e721086f8bd8f88984643c"
    sni: "www.nintendogames.net"
    skip-cert-verify: true
    udp: true
  - name: "Delta-Kronecker-vless-1555"
    type: vless
    server: "208.103.161.215"
    port: 2096
    uuid: "26524cce-d514-4014-a426-365fb266a14d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "WangCai.443888.xyz"
    network: ws
    ws-opts:
      path: "/danfeng?ed=2560&TelegramðŸ‡¨ðŸ‡³@WangCai2"
      headers:
        Host: "WangCai.443888.xyz"
  - name: "Delta-Kronecker-ss-008"
    type: ss
    server: "51.75.168.50"
    port: 13030
    cipher: "chacha20-ietf-poly1305"
    password: "6c815bb84c781da5"
    udp: true
  - name: "Delta-Kronecker-vless-4283"
    type: vless
    server: "89.116.88.19"
    port: 443
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.indevs.in"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³ @WangCai2"
      headers:
        Host: "sni.111000.indevs.in"
  - name: "Delta-Kronecker-ss-351"
    type: ss
    server: "209.126.5.209"
    port: 80
    cipher: "aes-256-gcm"
    password: "kEVKj1xvgzeEn8AV"
    udp: true
  - name: "Delta-Kronecker-vless-3434"
    type: vless
    server: "46.249.109.128"
    port: 443
    uuid: "6ec6da0f-008b-43fa-899d-d5cf147fe13a"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "q42m1wg11kZLyRtjaKus8T-NNl1vriRG3V1eVTL6ICc"
      short-id: "1b8d2fb1eec1"
  - name: "Delta-Kronecker-vless-2099"
    type: vless
    server: "54.36.98.93"
    port: 2053
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.111000.v6.navy"
    network: ws
    ws-opts:
      path: "/?ed=2560&TelegramðŸ‡¨ðŸ‡³ @WangCai2"
      headers:
        Host: "sni.111000.v6.navy"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "Delta-Kronecker-trojan-1159"
      - "Delta-Kronecker-trojan-469"
      - "Delta-Kronecker-vless-3042"
      - "Delta-Kronecker-vless-3962"
      - "Delta-Kronecker-vless-1248"
      - "Delta-Kronecker-trojan-1008"
      - "Delta-Kronecker-vless-4325"
      - "Delta-Kronecker-vless-2243"
      - "Delta-Kronecker-vless-324"
      - "Delta-Kronecker-vless-3677"
      - "Delta-Kronecker-vless-3777"
      - "Delta-Kronecker-vless-217"
      - "Delta-Kronecker-ss-2373"
      - "Delta-Kronecker-vless-3895"
      - "Delta-Kronecker-vless-3811"
      - "Delta-Kronecker-vless-3008"
      - "Delta-Kronecker-vless-1476"
      - "Delta-Kronecker-vless-2037"
      - "Delta-Kronecker-trojan-002"
      - "Delta-Kronecker-vless-1896"
      - "Delta-Kronecker-trojan-1180"
      - "Delta-Kronecker-vless-1555"
      - "Delta-Kronecker-ss-008"
      - "Delta-Kronecker-vless-4283"
      - "Delta-Kronecker-ss-351"
      - "Delta-Kronecker-vless-3434"
      - "Delta-Kronecker-vless-2099"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "Delta-Kronecker-trojan-1159"
      - "Delta-Kronecker-trojan-469"
      - "Delta-Kronecker-vless-3042"
      - "Delta-Kronecker-vless-3962"
      - "Delta-Kronecker-vless-1248"
      - "Delta-Kronecker-trojan-1008"
      - "Delta-Kronecker-vless-4325"
      - "Delta-Kronecker-vless-2243"
      - "Delta-Kronecker-vless-324"
      - "Delta-Kronecker-vless-3677"
      - "Delta-Kronecker-vless-3777"
      - "Delta-Kronecker-vless-217"
      - "Delta-Kronecker-ss-2373"
      - "Delta-Kronecker-vless-3895"
      - "Delta-Kronecker-vless-3811"
      - "Delta-Kronecker-vless-3008"
      - "Delta-Kronecker-vless-1476"
      - "Delta-Kronecker-vless-2037"
      - "Delta-Kronecker-trojan-002"
      - "Delta-Kronecker-vless-1896"
      - "Delta-Kronecker-trojan-1180"
      - "Delta-Kronecker-vless-1555"
      - "Delta-Kronecker-ss-008"
      - "Delta-Kronecker-vless-4283"
      - "Delta-Kronecker-ss-351"
      - "Delta-Kronecker-vless-3434"
      - "Delta-Kronecker-vless-2099"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "Delta-Kronecker-trojan-1159"
      - "Delta-Kronecker-trojan-469"
      - "Delta-Kronecker-vless-3042"
      - "Delta-Kronecker-vless-3962"
      - "Delta-Kronecker-vless-1248"
      - "Delta-Kronecker-trojan-1008"
      - "Delta-Kronecker-vless-4325"
      - "Delta-Kronecker-vless-2243"
      - "Delta-Kronecker-vless-324"
      - "Delta-Kronecker-vless-3677"
      - "Delta-Kronecker-vless-3777"
      - "Delta-Kronecker-vless-217"
      - "Delta-Kronecker-ss-2373"
      - "Delta-Kronecker-vless-3895"
      - "Delta-Kronecker-vless-3811"
      - "Delta-Kronecker-vless-3008"
      - "Delta-Kronecker-vless-1476"
      - "Delta-Kronecker-vless-2037"
      - "Delta-Kronecker-trojan-002"
      - "Delta-Kronecker-vless-1896"
      - "Delta-Kronecker-trojan-1180"
      - "Delta-Kronecker-vless-1555"
      - "Delta-Kronecker-ss-008"
      - "Delta-Kronecker-vless-4283"
      - "Delta-Kronecker-ss-351"
      - "Delta-Kronecker-vless-3434"
      - "Delta-Kronecker-vless-2099"

rules:
  - MATCH,PROXY
